# Generated by Django 2.0.2 on 2018-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=1000)),
                ('predicted', models.CharField(max_length=25)),
            ],
        ),
    ]
